apiVersion: apps/v1
kind: Deployment
metadata:
  name: erterhre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erterhre
  template:
    metadata:
      labels:
        app: erterhre
    spec:
      containers:
      - image: okteto.dev/erterhre:latest
        name: erterhre
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a29b0d8f-b135-49fa-a769-527b75955639"
        - name: Vless_Path
          value: "/jkdergueg34t7"
        - name: Vmess_UUID
          value: "a29b0d8f-b135-49fa-a769-527b75955639"
        - name: Vmess_Path
          value: "/uiytrhr45yeg45"
        - name: Share_Path
          value: "/v2link"
